import = [
# "~/.config/alacritty/themes/themes/challenger_deep.toml"
#  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  #"~/.config/alacritty/themes/themes/iris.toml"
  #"~/.config/alacritty/themes/themes/kanagawa_wave.toml"
  #"~/.config/alacritty/themes/themes/msx.toml"
  "~/.config/alacritty/themes/themes/oceanic_next.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 30
padding.y = 30

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hasklug Nerd Font"
size = 15
